project:
  namespace: "org.simplemodeling.textus"
  id: "Corpus"
  name: "textus-corpus"
  title: "Textus Corpus"
  kind: car
  scalaPackage: "org.simplemodeling.textus.corpus"
  component:
    name: "Corpus"
    className: "CorpusComponent"
    displayName: "Textus Corpus"
    version: "0.1.1-SNAPSHOT"

build:
  scalaVersion: "3.3.8"
  cozyVersion: "0.3.4-SNAPSHOT"
  dependencies:
    compile:
      - "org.goldenport::goldenport-cncf:0.5.2-SNAPSHOT"
    test:
      - "org.scalatest::scalatest:3.2.19"

publication:
  source_manifest:
    enabled: false

packaging:
  kind: car
  car:
    abi:
      dependencies: []
    manifest_metadata:
      boundedContext: "corpus"
      domain: "corpus-management"
    runtime:
      cncf:
        minimum: "0.5.2-SNAPSHOT"
        excluded: []
        tested:
          - "0.5.2-SNAPSHOT"

warehouse:
  repository_artifacts:
    include:
      - car
    modules:
      - "textus-corpus"
